//number guessing game
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main(void)
{



// introduction
	printf("Welcome to number guessing game\n");
	printf("you're going to guess a secret number generated by computer\n");
	printf("use the hints to find\n");



//declaring data types
	int number ;
	char decision;
	int input;



//loops the whole game
	while (1)
	{



		//generating  secret number
		srand(time(NULL));
		number = (rand()%100)+1;



		//loops the current game
		while(1)
		{

			printf("Your guess : ");
			if (scanf("%d",&input) != 1)
			{
				printf("Enter a valid number....");
				while(getchar() != '\n');
				continue;
			}
			if(input < number)
			{
				printf("TOO LOW \n");
			}
			else if(input > number)
			{
				printf("TOO HIGH \n ");
			}
			else
			{
				printf("\n==========\nYou guessed it !!!\n========== \n");
				break;
			}
		}// end of inner while loop



		//quit or continue
		printf("\n\nPress ENTER to play.....or 'q' to quit.");
		while(getchar() != '\n');
		decision=getchar();
		if (decision != '\n')
		{
			exit(0);
		}



	}// end of outer while loop	



	return 0;
}
